swagger: "2.0"
info:
  description: "Web-app scrapper information about Spain visa centers in Belarus."
  version: "1.0.0"
  title: "Spain scrapper"
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /visa-center:
    get:
      operationId: serv.read_visa_center
      tags:
        - Visa centers
      summary: Get the entire information of visa centers
      description: Read the list of visa centers
      responses:
        200:
          description: Successfully read visa centers list operation
          schema:
            type: array
            items:
              properties:
                Страна:
                  type: string
                Тип:
                  type: string
                Город:
                  type: string
                Адрес:
                  type: string
                Часы работы:
                  type: object
                  properties:
                    Время выдачи паспортов:
                      type: string
                    Время приема:
                      type: string
                Тел:
                  type: string
                почта:
                  type: string
                  
                

    post:
      operationId: serv.create_center
      tags:
        - Visa centers
      summary: Post a list of information about Spain visa centers
      description: Create a list of information about Spain visa centers
      responses:
        201:
          description: Successfully created visa centers list